### ISSUE TITLE
buffer layout

### ISSUE THREAD

**Issue by benjiqq** [raydium-io/raydium-idl#2]
instantiating coder

```
const coder = new RaydiumAmmCoder(idl as Idl);
const result = coder.instruction.decode(
    Buffer.from("0bf70a9c01000000006417427900000000", "hex")
);
console.log(result);

```

seems like issue with layout here
https://github.com/raydium-io/raydium-idl/blob/master/raydium_amm/src/coder/accounts.ts#L109

```
$ ts-node src/index.ts
TypeError: fields must be array of Layout instances
    at new Structure (/Users/ben/projects/polaris/monitor/node_modules/@native-to-anchor/buffer-layout/node_modules/@solana/buffer-layout/src/Layout.ts:1107:13)
    at Object.exports.struct (/Users/ben/projects/polaris/monitor/node_modules/@native-to-anchor/buffer-layout/node_modules/@solana/buffer-layout/src/Layout.ts:2615:5)
    at Object.<anonymous> (/Users/ben/projects/polaris/monitor/src/raydium/coder/accounts.ts:109:32)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module.m._compile (/Users/ben/projects/polaris/monitor/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/ben/projects/polaris/monitor/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by 336fran** [comment]
Same error.

Is there any solution for this issue or another way to decode the data from the program?

**Comment by zLikeMario** [comment]
Do you have a solution?

**Comment by rishenco** [comment]
Hi
I have this issue too
@benjiqq @YaminZheng  @336fran  Did you find a work around?

**Comment by msrrxsgx** [comment]
The issue with the '@ solana/buffer layout' version can be resolved by installing the specified version 4.0.0
npm i @solana/ buffer-layout@4.0.0

**Comment by BoogalooLi** [comment]
> npm i @solana/buffer-layout@4.0.0

it does work. Thank you very much.

**Comment by Saty248** [comment]
not working for me. still getting the same error after i upgraded
